### ISSUE TITLE
CLI Microphone/Speaker Argument Broken

### ISSUE THREAD

**Issue by ModelWorldLLC** [sabeechen/rpi-intercom#1]
When providing the speaker and microphone arguments in a yaml config file, they are passed as strings, and the validation at devices.py:265 works as expected.

When passed as command line arguments (say, while figuring out correct settings before making the config file), they appear to be passed as lists, so devices.py ends up comparing "device name" with "['device name']" and fails. I'm SSHed into my rpi from WSL Ubuntu, though I wouldn't expect that to make a difference here.

If I have time in the next couple days I'll write a patch and submit a PR. 

Thank you so much for this project, though; it saved me a *lot* of tinkering to setup an intercom system.

**Comment by sabeechen** [comment]
Congrats on creating issue number one! 🎉  

It looks like a bunch of the command line arguments get unintentionally parsed as arrays because I got a little copy-paste happy when I wrote the argument parser.  I'll fix it.

**Comment by sabeechen** [comment]
Fixed in version 0.0.19
